### PR TITLE
✨ Added status code colours to prettysteam output

### PR DESCRIPTION
**Pull request by ErisDS**
With this PR + https://github.com/TryGhost/Ghost/pull/8850, the output looks like:

no issue

- Add colors for status code, the same as morgan
- This makes the status code output in a colour, exactly the same as LTS

### CODE REVIEW

**Review by acburdine — APPROVED** [review]
LGTM 👍  -> tests just need a fix b/c they check colors

**Comment by kirrg001** [comment]
Pretty cool 👍

**Comment by ErisDS** [comment]
Will look at the tests now.

**Comment by ErisDS** [comment]
Fixed 😬

**Review by kirrg001 — APPROVED** [review]

**Pull request merged**
