### PR TITLE
🛠 Used full paths for tools in npm scripts

### PR DESCRIPTION
**Pull request by ErisDS**
no issue

- This means I don't have to have mocha & eslint installed globally

### CODE REVIEW

**Review by acburdine — COMMENTED** [review]
Are you sure these changes are necessary? `npm run x` auto-prepends the bin path to anything that's run, so it _should_ just work out of the box.

**Comment by ErisDS** [comment]
It complained about no eslint & this is how we do this in every other project - hence I added it. Might be that I hadn't run npm install tho 🤔

**Comment by ErisDS** [comment]
> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write:

Seems like this is something we missed in npm docs: https://docs.npmjs.com/cli/run-script

**Comment by sebgie** [comment]
This didn't work in the past (> 1 year ago) but was added to npm 🎉 .

**Pull request closed without merging**
