### PR TITLE
fix(prettystream): make prettystream a proper transform stream

### PR DESCRIPTION
**Pull request by acburdine**
refs #27
- convert PrettyStream to extend WriteStream and fix some potential bugs

### CODE REVIEW

**Comment by acburdine** [comment]
@kirrg001 ~~I didn't test this with Ghost or knex-migrator, but it _should_ (:tm:) work the same~~ tested with Ghost.

**Comment by kirrg001** [comment]
`npm test` is red

**Comment by kirrg001** [comment]
Have added travis, just need to enable it later, have no permissions 👍

**Comment by kirrg001** [comment]
Travis is enabled now.

**Comment by acburdine** [comment]
@kirrg001 _completely_ missed the `test` folder in the repo 😛 . Should be good now :)

**Comment by kirrg001** [comment]
> completely missed the test folder in the repo

was definitely my fault as well, because i forgot to enable travis 🙈

**Comment by kirrg001** [comment]
Getting an error when installing your tarball.
I think it's the case of an error. Because my Ghost DB was not initialised.

$ node index.js
Unhandled rejection TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:185:14)
    at PrettyStream.Writable.write (_stream_writable.js:212:12)
    at Logger._emit (/Users/kirrg001/dev/ghost/ghost/node_modules/bunyan/lib/bunyan.js:939:22)
    at Logger.error (/Users/kirrg001/dev/ghost/ghost/node_modules/bunyan/lib/bunyan.js:1061:24)
    at /Users/kirrg001/dev/ghost/ghost/node_modules/ghost-ignition/lib/logging/GhostLogger.js:267:29
    at /Users/kirrg001/dev/ghost/ghost/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/Users/kirrg001/dev/ghost/ghost/node_modules/lodash/_baseForOwn.js:13:20)
    at /Users/kirrg001/dev/ghost/ghost/node_modules/lodash/_createBaseEach.js:17:14
    at forEach (/Users/kirrg001/dev/ghost/ghost/node_modules/lodash/forEach.js:38:10)
    at GhostLogger.log (/Users/kirrg001/dev/ghost/ghost/node_modules/ghost-ignition/lib/logging/GhostLogger.js:259:5)
    at GhostLogger.error (/Users/kirrg001/dev/ghost/ghost/node_modules/ghost-ignition/lib/logging/GhostLogger.js:281:10)
    at /Users/kirrg001/dev/ghost/ghost/index.js:44:13
    at tryCatcher (/Users/kirrg001/dev/ghost/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kirrg001/dev/ghost/ghost/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/kirrg001/dev/ghost/ghost/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/kirrg001/dev/ghost/ghost/node_modules/bluebird/js/release/promise.js:612:10)

**Comment by acburdine** [comment]
@kirrg001 It appears Bunyan abuses write streams a bit.....have updated it to work around Bunyan passing objects to the stream.

**Review by kirrg001 — APPROVED** [review]

**Comment by kirrg001** [comment]
Works now 👍 Tested some basic use cases with Ghost.

**Pull request merged**
