### PR TITLE
🎨 redesign errors

### LINKED ISSUE #6: error design
The current error design is not good enough.

```
err = new errors.NoPermissionError()
err instanceof errors.NoPermissionError
err instanceof Error
```

Both are never true.
That is because: the `new` operator is used for the function `errors.NoPermissionError` and not for the wrapped created error.

Another thing:
https://github.com/TryGhost/Patronus/blob/master/test/unit/lib_oauth.test.js#L165
Let's not compare strings!When doing a global rename, these strings are NOT affected.

### PR DESCRIPTION
**Pull request by kirrg001**
closes #6 

Ignition will offer a set of errors, as it did before.

If you would like to use the error feature, you have the following features:
- you can create your own custom general error and inherit from IgnitionError
- you can add more custom errors

Let's look at how this looks like. This is an error file in your project, which wraps Ignition.

```
function GhostError(options) {
   // Ghost is able to add more custom properties
   this.property = options.property;
   this.value = options.value;

   errors.IgnitionError.call(this, options);
}

// Ghost is able to add more custom errors
var ghostErrors = {
    CustomGhostError: function CustomGhostError(options) {
        GhostError.call(this, _.merge({
             statusCode: 500,
             errorType: 'CustomGhostError'
        }, options));
     }
};

// merge all errors together
_.merge(ghostErrors, errors);

// lets inherit all errors from GhostError
util.inherits(GhostError, errors.IgnitionError);
_.each(ghostErrors, function (error) {
    util.inherits(error, GhostError);
});

module.exports = ghostErrors;
module.exports.GhostError = GhostError;
```

This code was tested with Patronus.

### CODE REVIEW

**Comment by ErisDS** [comment]
2 comments:
1. I think it might be worth doing a patch release with the logging changes, and then doing a minor release with this change. Logging is not breaking, this one is ;)
2. This removes the default messages, was there a reason for that change?

**Comment by ErisDS** [comment]
To further explain 1. there are several libraries dependent on this one that will benefit from the logging changes, but forcing them to change their error format at the same time is not ideal. Unless both are absolutely required?

**Comment by kirrg001** [comment]
> 1. I think it might be worth doing a patch release with the logging changes, and then doing a minor release with this change. Logging is not breaking, this one is ;)

Ok let's do that. But it's minor (for logging) and major (for errors), or?Errors is an Ignition API change. Logging is a new feature. 

> 1. This removes the default messages, was there a reason for that change?

Sorry I forgot to add the reasoning why. I dropped it, because i saw that we are not relying on default messages anywhere. But let me re-add it, i think it's nice to have them just in case.

**Comment by kirrg001** [comment]
> To further explain 1. there are several libraries dependent on this one that will benefit from the logging changes, but forcing them to change their error format at the same time is not ideal. Unless both are absolutely required?

The only reason i can see for releasing them together is: logging won't play well with the old error implementation of Ignition (for example the missing Inheritance of Error)

**Comment by ErisDS** [comment]
> Ok let's do that. But it's minor (for logging) and major (for errors), or?Errors is an Ignition API change. Logging is a new feature.

Ignition is still pre-1.0.0?  

> The only reason i can see for releasing them together is: logging won't play well with the old error implementation of Ignition (for example the missing Inheritance of Error)

Won't play well = doesn't work at all or doesn't work nicely?

Either way, we need to get Patronus upgraded asap as that's pretty much blocking now, and I will also do the new API lib I'm working on. Then we need to go around and look at all the other places that Ignition is used (knex-migrator, gscan, etc?)

**Comment by kirrg001** [comment]
Ok. How about agreeing on a `pre-1.0.0` with both features (logging and error design)?
I have everything in place for Patronus, i just need to make clean commits. Then we can merge my PR in Patronus. You can go on with new API lib and i can go with using the new Ignition version in all other projects (especially passport-ghost)

**Comment by ErisDS** [comment]
> How about agreeing on a pre-1.0.0 with both features (logging and error design)?

Not sure what that solves? If you've got everything done for Patronus then we might as well go for it with the 1.0.0 bump.

**Comment by kirrg001** [comment]
I've added the default messages and added a test to ensure default vs. custom messages work.
I will self-merge now and release a `1.0.0` with both features. If we encounter any problems, we can fix them easily.

**Pull request merged**
